### ISSUE TITLE
charset iso-2022-jp-2

### ISSUE THREAD

**Issue by jonasgit** [abelsson/androkom#34]
Probably can't read texts encoded with iso-2022-jp-2. See text 18865435 and 18178867.

**Comment by jonasgit** [comment]
I/androkom( 8245): fetching parent to text 18865435
D/Androkom KomServer( 8245): getTextAsHTML
java.io.UnsupportedEncodingException: iso-2022-jp-2
W/System.err( 8245): java.io.UnsupportedEncodingException: iso-2022-jp-2
W/System.err( 8245): at java.lang.String.getCharset(String.java:972)
W/System.err( 8245): at java.lang.String.<init>(String.java:393)
W/System.err( 8245): at java.lang.String.<init>(String.java:429)
W/System.err( 8245): at
org.lysator.lattekom.Text.getSubjectString(Text.java:445)
W/System.err( 8245): at
org.lindev.androkom.KomServer.getKomText(KomServer.java:490)
W/System.err( 8245): at
org.lindev.androkom.KomServer.getParentToText(KomServer.java:432)
W/System.err( 8245): at
org.lindev.androkom.Conference$LoadMessageTask.doInBackground(Conference.java:124)
W/System.err( 8245): at
org.lindev.androkom.Conference$LoadMessageTask.doInBackground(Conference.java:1)
W/System.err( 8245): at android.os.AsyncTask$2.call(AsyncTask.java:185)
W/System.err( 8245): at
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
W/System.err( 8245): at
java.util.concurrent.FutureTask.run(FutureTask.java:137)
W/System.err( 8245): at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
W/System.err( 8245): at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
W/System.err( 8245): at java.lang.Thread.run(Thread.java:1096)
W/System.err( 8245): Caused by:
java.nio.charset.UnsupportedCharsetException: The unsupported charset name
is "iso-2022-jp-2".
W/System.err( 8245): at java.nio.charset.Charset.forName(Charset.java:544)
W/System.err( 8245): at java.lang.String.getCharset(String.java:967)
W/System.err( 8245): ... 13 more

**Comment by jonasgit** [comment]
Change to not throw exception but show as if iso-8859-1 encoded.
